# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ENews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Bla bla bla!', verbose_name='title')),
                ('text', models.TextField(default='bla bla bla', verbose_name='text')),
                ('expodate', models.DateField(verbose_name='expo_date')),
                ('expotheme', models.TextField(default='Nature', verbose_name='expo_theme')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Awesome Gallery', verbose_name='name')),
                ('address', models.TextField(default='Some Street, 3', verbose_name='address')),
                ('lat', models.FloatField(verbose_name='lattitude')),
                ('lng', models.FloatField(verbose_name='longtitude')),
            ],
        ),
        migrations.CreateModel(
            name='PhysNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begintime', models.TimeField(verbose_name='begin_time')),
                ('price', models.IntegerField(default=100, verbose_name='price')),
                ('galleries', models.ManyToManyField(to='netart.PhysGallery')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netart.News')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Some Awesome Picture', verbose_name='title')),
                ('uploaddate', models.DateField(verbose_name='upload_date')),
                ('theme', models.TextField(default='Nature', verbose_name='theme')),
                ('ratecount', models.IntegerField(default=10, verbose_name='rate_count')),
                ('style', models.TextField(default='Aerography', verbose_name='style')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='M', max_length=1, verbose_name='gender')),
                ('city', models.TextField(default='Kyiv', verbose_name='city')),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('status', models.TextField(default='User', verbose_name='status')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netart.Profile')),
                ('theme', models.TextField(default='Nature', verbose_name='theme')),
                ('picsuploaded', models.IntegerField(default=1, verbose_name='pictures_uploaded')),
                ('messages', models.IntegerField(default=1, verbose_name='messages')),
                ('style', models.TextField(default='Aerography', verbose_name='style')),
            ],
            bases=('netart.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netart.News'),
        ),
    ]
