# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'User'), ('artist', 'Artist')], default='User', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
