# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0002_auto_20170522_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='style',
            field=models.CharField(blank=True, default='Aerography', max_length=64, verbose_name='style'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='theme',
            field=models.CharField(blank=True, default='Nature', max_length=64, verbose_name='theme'),
        ),
        migrations.AlterField(
            model_name='news',
            name='expotheme',
            field=models.CharField(blank=True, default='Nature', max_length=64, verbose_name='expo_theme'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(blank=True, default='bla bla bla', max_length=64, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, default='Bla bla bla!', max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='physgallery',
            name='address',
            field=models.CharField(blank=True, default='Some Street, 3', max_length=64, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='physgallery',
            name='name',
            field=models.CharField(blank=True, default='Awesome Gallery', max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='style',
            field=models.CharField(blank=True, default='Aerography', max_length=64, verbose_name='style'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='theme',
            field=models.CharField(blank=True, default='Nature', max_length=64, verbose_name='theme'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, default='Some Awesome Picture', max_length=64, verbose_name='title'),
        ),
    ]
