# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0003_auto_20170526_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physnews',
            name='galleries',
        ),
        migrations.DeleteModel(
            name='PhysGallery',
        ),
    ]
