# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0004_auto_20170603_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='arts/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='avatars/', verbose_name='image'),
        ),
    ]
