# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0005_auto_20170604_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='uploaddate',
        ),
        migrations.AddField(
            model_name='picture',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='uploaded_at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='expodate',
            field=models.DateField(null=True, verbose_name='expo_date'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='ratecount',
            field=models.IntegerField(default=0, verbose_name='rate_count'),
        ),
    ]
