# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0007_auto_20170605_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='authors',
        ),
    ]
