# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0008_remove_news_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(blank=True, default='bla bla bla', max_length=500, verbose_name='text'),
        ),
    ]
