# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netart', '0009_auto_20170606_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, default='Bla bla bla!', max_length=100, verbose_name='title'),
        ),
    ]
